Сохранять все таски в файл и восстанавливать из файла
iozimniy/java-kanban pull request #2
Opened 2024-07-13 23:54 UTC by iozimniy

2024-07-14 17:00 UTC, EugeneLenkevich requested changes
Привет, Мария! Спасибо за PR.

Отличная работа! :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

2024-07-14 17:00 UTC, EugeneLenkevich commented on src/ru/practicum/javakanban/manager/FileBackedTaskManager.java
> +            case "TASK" -> new Task(parameters[2], parameters[4], Integer.parseInt(parameters[0]),
parameters[2]

Думаю стоит переложить сначала эти значения в переменные с говорящими названиями, иначе, если формат поменяется, то будет довольно трудно разобраться в том где какие данные хранятся  :)

2024-07-14 17:00 UTC, EugeneLenkevich commented on src/ru/practicum/javakanban/manager/FileBackedTaskManager.java
> +            throw new ManagerSaveException("Внимание: рак на горе свистнул!");
ManagerSaveException

Можно завести аналогичное исключение ManagerLoadException, а то получается что при загрузке (это же загрузка, не перепутал?) данных падает исключение сохранения данных, может путать :)

2024-07-14 17:00 UTC, EugeneLenkevich commented on src/ru/practicum/javakanban/manager/FileBackedTaskManager.java
> +    public FileBackedTaskManager(HistoryManager historyManager, File taskManagerCsv) {
Кстати, у нас есть статический метод для создания менеджера. Этот конструктор можно сделать приватным, тогда мы оставим только один способ создания менеджера - через тот метод. Это сделает наш код более простым потому что будет меньше лишних вариантов возможных действий :)

2024-07-14 17:00 UTC, EugeneLenkevich commented on src/ru/practicum/javakanban/model/Epic.java
> +    private final TaskType type = TaskType.EPIC;
Да можно не хранить тип в отдельном поле, а сразу в get-методе возвращать значение enum, у нас же типы просто так не меняются :)

2024-07-14 17:00 UTC, EugeneLenkevich commented on test/ru/practicum/javakanban/manager/FileBackedTaskManagerTests.java
> +        } catch (IOException e) {
В тесте можно не перехватывать исключение, junit и так распечатает стректейс ошибки :)

2024-07-16 21:29 UTC, iozimniy commented on src/ru/practicum/javakanban/manager/FileBackedTaskManager.java
> +    public FileBackedTaskManager(HistoryManager historyManager, File taskManagerCsv) {
> Кстати, у нас есть статический метод для создания менеджера. Этот конструктор можно сделать приватным, тогда мы оставим только один способ создания менеджера - через тот метод. Это сделает наш код более простым потому что будет меньше лишних вариантов возможных действий :)

Вот этот момент не понятен. Наш статический метод создания менеджера как раз использует этот конструктор. Если мы сделаем конструктор приватным, у статического метода не будет к нему доступа.
Или я неверно поняла идею.

2024-07-17 03:15 UTC, EugeneLenkevich commented on src/ru/practicum/javakanban/manager/FileBackedTaskManager.java
> +    public FileBackedTaskManager(HistoryManager historyManager, File taskManagerCsv) {
Вроде же должен остаться доступ, в том же классе объявлен статический метод, могу конечно ошибаться

2024-07-17 03:20 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2024-07-17 03:20 UTC, EugeneLenkevich commented on src/ru/practicum/javakanban/manager/FileBackedTaskManager.java
> +            switch (headers[i]) {
Серьезный подход, прямо порадовал, и его еще улучшить можно, вместо  пачки переменных завести мапу Map<String, Integer>, в целом то де самое, только короче :)

2024-07-17 14:48 UTC, EugeneLenkevich commented on src/ru/practicum/javakanban/manager/FileBackedTaskManager.java
> +    public FileBackedTaskManager(HistoryManager historyManager, File taskManagerCsv) {
Что то стал сомневаться, пошел перепроверил, да, все верно, вот примерно так 
![image](https://github.com/user-attachments/assets/5b884f4d-4d77-4317-aac3-ad7129b57209)

![image](https://github.com/user-attachments/assets/fb25982f-ed84-4238-a6bc-e951230d8804)

![image](https://github.com/user-attachments/assets/9bd1310d-65bd-4b8e-8d53-ef8cdce718cb)

2024-07-17 16:48 UTC, merged