Sprint 8 solution time and duration
iozimniy/java-kanban pull request #4
Opened 2024-08-29 22:44 UTC by iozimniy

2024-08-30 09:01 UTC, EugeneLenkevich requested changes
Привет, Мария! Спасибо за PR.

Совсем небольшой момент - давай разберемся с исключением, которое выбрасывается в случае пересечения задач. И еще можно на эту ситуацию, выброс исключения (см. assertThrows), написать отдельный тест, если его, конечно, еще нет  :)

https://habr.com/ru/articles/591305/

2024-08-30 09:01 UTC, EugeneLenkevich commented on src/ru/practicum/javakanban/manager/InMemoryTaskManager.java
> +        return prioritizedTasks.stream().toList();
В принципе можно в список и не перекладывать, а из метода возвращать Collection<Task>. Просто меньше действий

2024-08-30 09:01 UTC, EugeneLenkevich commented on src/ru/practicum/javakanban/exeptions/ManagerPrioritizeException.java
> +public class ManagerPrioritizeException extends RuntimeException {
extends RuntimeException

RuntimeException - непроверяемое(unchecked) исключение, оно означает что в логике произошла нештатная ситуация и состояние стало неконсистентным (так же как и NullPointerException, например).
Однако, пересечение задач более чем штатная, предсказуемая, ситуация. Здесь стоит кидать проверяемое (checked) исключение, throw new Exception(...) (ну и обработать его выше по стеку, на то оно и проверяемое =)

2024-08-30 10:34 UTC, iozimniy commented
> Привет, Мария! Спасибо за PR.
> 
> Совсем небольшой момент - давай разберемся с исключением, которое выбрасывается в случае пересечения задач. И еще можно на эту ситуацию, выброс исключения (см. assertThrows), написать отдельный тест, если его, конечно, еще нет :)
> 
> https://habr.com/ru/articles/591305/

Привет, Евгений.) Тест, конечно, есть.

2024-08-31 15:36 UTC, iozimniy commented on src/ru/practicum/javakanban/manager/InMemoryTaskManager.java
> +        return prioritizedTasks.stream().toList();
> В принципе можно в список и не перекладывать, а из метода возвращать Collection. Просто меньше действий

Евгений, поясните, пожалуйста, этот момент. Если мы хотим вернуть список с задачами, расположенными в этом списке в последовательности от самой ранней до самой поздней по полю startTime, и далее, возможно, использовать удобные методы списка, такие как getFirst(), зачем нам возвращать коллекцию?

2024-09-03 04:59 UTC, EugeneLenkevich commented on src/ru/practicum/javakanban/manager/InMemoryTaskManager.java
> +        return prioritizedTasks.stream().toList();
> Евгений, поясните, пожалуйста, этот момент. Если мы хотим вернуть список с задачами, расположенными в этом списке в последовательности от самой ранней до самой поздней по полю startTime, и далее, возможно, использовать удобные методы списка, такие как getFirst(), зачем нам возвращать коллекцию?
> 
> В ТЗ просили список...

Ну смотри, по факту упорядоченный набор объектов у нас есть потому и можно его вернуть как Collection без дополнительной логики перекладывания.
Но на самом деле не критично, можно и List оставить

2024-09-03 10:39 UTC, iozimniy commented on src/ru/practicum/javakanban/manager/InMemoryTaskManager.java
> +        return prioritizedTasks.stream().toList();
> > Евгений, поясните, пожалуйста, этот момент. Если мы хотим вернуть список с задачами, расположенными в этом списке в последовательности от самой ранней до самой поздней по полю startTime, и далее, возможно, использовать удобные методы списка, такие как getFirst(), зачем нам возвращать коллекцию?
> > В ТЗ просили список...
> 
> Ну смотри, по факту упорядоченный набор объектов у нас есть потому и можно его вернуть как Collection без дополнительной логики перекладывания. Но на самом деле не критично, можно и List оставить

Оставила List, если ты не против.)

2024-09-03 11:02 UTC, EugeneLenkevich requested changes
Привет, давай немножко работу с исключениями допилим, а так все гут

2024-09-03 11:02 UTC, EugeneLenkevich commented on src/ru/practicum/javakanban/manager/FileBackedTaskManager.java
> +                        throw new RuntimeException(e);
Прочему появился такой код понятно, из-за особенностей стримов, связанных с обратной совместимостью, однако, можно это достаточно элегантно обойти
вот это

strings.stream().forEach(string -> { ...

заменить на 
for(String string : strings) { ...

и тогда у нас и код станет красивей, не придется возится с пробросом исключений. Вообще, не всегда использование стримов оправдано и этот как раз тот случай. Суть стримов - сделать код проще, а он тут усложняется. Так что лучше стрим убрать вовсе :)

Хотя, можно сказать, что все равно не надо падать в случае ошибки так как если мы не прочитали пользовательские данные то и стартовать смысла нет (fail-fast). Пользовательские данные повреждены, пусть узнает как можно раньше. Но и тогда лучше кидать не RuntimeException, а наше ManagerLoadException, мы как раз ля этого его и создавали

И, вообще, наверно стоит скомбинировать оба похода - обернуть в try-catch всю логику загрузки данных, заменить стрим, ловить проверяемое исключение и кидать наше непроверяемое. В принципе это то же самое, но сейчас перехват исключения дублируется, хочется все таки чтобы этот перехват был только один раз :)

2024-09-04 09:16 UTC, EugeneLenkevich approved these changes
Ну красота же получилась :)

2024-09-09 20:44 UTC, merged